name: CI Pipeline

on:
  push:
    branches:
      - main
env:
  IMAGE_REPO: ghcr.io/scottaubrey/test-app

jobs:
  generate-version:
    runs-on: ubuntu-latest
    outputs:
      trunkver: ${{ steps.trunkver.outputs.trunkver }}
    steps:
      - name: Get a version tag
        id: trunkver
        uses: crftd-tech/trunkver@main
        with:
          prerelease: ${{ github.ref == 'refs/heads/master' && 'false' || 'true' }}
  build-and-push:
    needs: [generate-version]
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.ref == 'refs/heads/master' && needs.generate-version.outputs.trunkver }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push client image
        uses: docker/build-push-action@v6
        with:
          push: true
          load: false
          platforms: linux/amd64,linux/arm64
          build-args: |
            git_rev=${{ github.sha }}
          tags: |
            ${{ env.IMAGE_REPO }}:${{ github.sha }}
            ${{ env.IMAGE_REPO }}:${{ env.IMAGE_TAG }}
